services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elastic
    hostname: elastic
    ports:
      - "9200:9200"
    environment:
      xpack.security.enabled: "false"
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
