version: '3'

services:
  surreal:
    image: surrealdb/surrealdb
    container_name: surreal
    hostname: surreal
    restart: always
    entrypoint:
      - /surreal
      - start
      - -l
      - trace
      - --auth
      - -u
      - root
      - -p
      - root
      - memory
      - -A
    ports:
      - 8000:8000
