version: '3'

services:
  surreal:
    image: surrealdb/surrealdb
    container_name: surreal
    hostname: surreal
    restart: always
    entrypoint:
      - /surreal
      - start
      - --log
      - trace
      - --auth
      - memory
      - --allow-all
    ports:
      - 8000:8000
