version: '3.5'
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    restart: unless-stopped
