services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
